import {calculateFundSnapshot,calculatePortfolioSnapshot,buildSeries,latestCommonObservations} from './portfolio.js';
import {renderLineChart} from './chart.js';
import {decodeBootstrapHash,normalizeHoldings} from './config.js';
import {formatCurrency,formatPercent,formatNav,formatDate,signClass} from './format.js';
const STORAGE_KEY='myFundDashboardHoldingsV1';
const FUND_META={RBF460:{code:'RBF460',name:'RBC Select Balanced Portfolio',account:'TFSA',purchaseDate:'2026-08-31'},RBF266:{code:'RBF266',name:'RBC Canadian Dividend Fund',account:'Non-registered',purchaseDate:'2026-08-31'}};
const state={history:null,holdings:null,selection:'TOTAL',metric:'value'};const $=(id)=>document.getElementById(id);
function showStatus(message){const n=$('statusBanner');n.textContent=message;n.classList.remove('hidden');}
function loadLocalHoldings(){try{const boot=decodeBootstrapHash(window.location.hash);if(boot){localStorage.setItem(STORAGE_KEY,JSON.stringify(boot));history.replaceState(null,'',`${location.pathname}${location.search}`);return boot;}const raw=localStorage.getItem(STORAGE_KEY);return raw?normalizeHoldings(JSON.parse(raw)):null;}catch(e){showStatus(`Portfolio settings could not be loaded: ${e.message}`);return null;}}
function latestPair(rows){const sorted=[...(rows||[])].sort((a,b)=>a.date.localeCompare(b.date));return{latest:sorted.at(-1)??null,previous:sorted.at(-2)??null};}
function setSigned(node,value,formatter){node.textContent=formatter(value,true);node.className=signClass(value);}
function renderSummary(){const common=latestCommonObservations(state.history,Object.keys(FUND_META)),latestDate=common.latestDate;$('valuationDate').textContent=latestDate?`Latest common published NAV · ${formatDate(latestDate)}`:'Latest published NAV unavailable';$('latestDateMini').textContent=latestDate?`Portfolio as of ${formatDate(latestDate)}`:'';$('dataUpdatedAt').textContent=state.history.updatedAt?`Data file updated ${new Date(state.history.updatedAt).toLocaleString()}`:'';if(!state.holdings){$('portfolioValue').textContent='NAV ready';$('portfolioGain').textContent='Save holdings';$('portfolioReturn').textContent='—';$('portfolioDaily').textContent='—';$('setupCta').classList.remove('hidden');return;}$('setupCta').classList.add('hidden');if(!common.latestDate){showStatus('A common valuation date is not yet available for both funds.');return;}const snap=calculatePortfolioSnapshot(state.holdings,common.latest,common.previous);$('portfolioValue').textContent=formatCurrency(snap.value);setSigned($('portfolioGain'),snap.gainLoss,formatCurrency);setSigned($('portfolioReturn'),snap.returnPct,formatPercent);$('portfolioDaily').textContent=snap.dailyValueChange==null?'—':`${formatCurrency(snap.dailyValueChange,true)} (${formatPercent(snap.dailyValueChangePct,true)})`;$('portfolioDaily').className=signClass(snap.dailyValueChange);}
function renderFunds(){const c=$('fundCards');c.replaceChildren();for(const code of Object.keys(FUND_META)){const meta=FUND_META[code],{latest,previous}=latestPair(state.history.funds[code]);if(!latest)continue;const card=document.createElement('article');card.className='fund-card';let personal=null;if(state.holdings)personal=calculateFundSnapshot(state.holdings[code],latest,previous);const dailyChange=previous?latest.nav-previous.nav:null,dailyPct=previous?(dailyChange/previous.nav)*100:null;card.innerHTML=`<div class="fund-title"><div><span class="fund-code">${code}</span><h3>${meta.name}</h3></div><div class="nav-block"><strong>${formatNav(latest.nav)}</strong><small>${formatDate(latest.date)}</small></div></div><div class="fund-metrics"><div class="metric"><span>Daily NAV</span><strong class="${signClass(dailyChange)}">${dailyChange==null?'—':`${dailyChange>0?'+':''}${dailyChange.toFixed(4)} (${formatPercent(dailyPct,true)})`}</strong></div><div class="metric"><span>Current value</span><strong>${personal?formatCurrency(personal.value):'Set holdings'}</strong></div><div class="metric"><span>Gain / loss</span><strong class="${personal?signClass(personal.gainLoss):'neutral'}">${personal?formatCurrency(personal.gainLoss,true):'—'}</strong></div><div class="metric"><span>Return</span><strong class="${personal?signClass(personal.returnPct):'neutral'}">${personal?formatPercent(personal.returnPct,true):'—'}</strong></div><div class="metric"><span>Purchase NAV</span><strong>${personal?formatNav(personal.purchaseNav):'—'}</strong></div><div class="metric"><span>Units</span><strong>${personal?personal.units.toFixed(4):'—'}</strong></div></div>`;c.appendChild(card);}}
function renderChart(){const svg=$('performanceChart'),empty=$('chartEmpty');if(!state.holdings){svg.replaceChildren();empty.classList.remove('hidden');$('chartLatest').textContent='—';return;}empty.classList.add('hidden');const series=buildSeries(state.history,state.holdings,state.selection,state.metric),isReturn=state.metric==='return',formatter=isReturn?(v)=>formatPercent(v):(v)=>formatCurrency(v);renderLineChart(svg,series,{formatY:formatter,ariaLabel:`${state.selection} ${state.metric} since purchase`});const last=series.at(-1);$('chartLatest').textContent=last?formatter(last.value):'—';$('chartSubtitle').textContent=`${state.selection==='TOTAL'?'Total portfolio':state.selection} · ${isReturn?'Cumulative return':'Portfolio value'}`;$('chartUnit').textContent=isReturn?'%':'CAD';}
function fillSettingsForm(){const form=$('settingsForm'),h=state.holdings;for(const code of Object.keys(FUND_META)){const current=h?.[code];form.elements[`${code}_units`].value=current?.units??'';form.elements[`${code}_contribution`].value=current?.contribution??'';form.elements[`${code}_purchaseNav`].value=current?.purchaseNav??'';}}
function openSettings(){fillSettingsForm();$('settingsDialog').showModal();}
function saveSettings(event){event.preventDefault();const form=new FormData(event.currentTarget),raw={};for(const code of Object.keys(FUND_META)){raw[code]={...FUND_META[code],units:Number(form.get(`${code}_units`)),contribution:Number(form.get(`${code}_contribution`)),purchaseNav:Number(form.get(`${code}_purchaseNav`))};}try{state.holdings=normalizeHoldings(raw);localStorage.setItem(STORAGE_KEY,JSON.stringify(state.holdings));$('settingsDialog').close();renderAll();}catch(e){showStatus(e.message);}}
function clearSettings(){localStorage.removeItem(STORAGE_KEY);state.holdings=null;$('settingsDialog').close();renderAll();}
function bindControls(){$('settingsButton').addEventListener('click',openSettings);$('setupCta').addEventListener('click',openSettings);$('closeSettings').addEventListener('click',()=>$('settingsDialog').close());$('clearSettings').addEventListener('click',clearSettings);$('settingsForm').addEventListener('submit',saveSettings);$('fundSelector').addEventListener('click',(event)=>{const b=event.target.closest('button[data-selection]');if(!b)return;state.selection=b.dataset.selection;for(const x of $('fundSelector').querySelectorAll('button'))x.classList.toggle('active',x===b);renderChart();});$('metricSelector').addEventListener('click',(event)=>{const b=event.target.closest('button[data-metric]');if(!b)return;state.metric=b.dataset.metric;for(const x of $('metricSelector').querySelectorAll('button'))x.classList.toggle('active',x===b);renderChart();});}
function renderAll(){renderSummary();renderFunds();renderChart();}
async function init(){bindControls();state.holdings=loadLocalHoldings();try{const response=await fetch(`data/nav-history.json?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);state.history=await response.json();const latest=Object.values(state.history.funds).flat().map((x)=>x.date).sort().at(-1);if(latest){const daysOld=(Date.now()-new Date(`${latest}T23:59:59Z`).getTime())/86400000;if(daysOld>4)showStatus(`The latest NAV is ${formatDate(latest)}. The automatic update may be delayed.`);}renderAll();}catch(e){showStatus(`NAV data could not be loaded: ${e.message}`);}}
init();
